### ISSUE TITLE
Failed to add new OS support due to errors when `vagrant up --provision`

### ISSUE THREAD

**Issue by weijianwen** [voxpupuli/facterdb#288]
I'm trying to add OpenEuler 23 as a supported OS by Puppet. But I failed in `vagrant up --provision` when following instructions to add more OS facter into facterdb.

https://github.com/voxpupuli/puppet-yum/pull/322

I tried this on OpenEuler 22.03 (x86_64) + VirtualBox 6.1  + Vagrant 2.3.7 .  Steps to reproduce this issue are:

1. Install VirtualBox and Vagrant.
2. Clone facterdb by `git clone https://github.com/voxpupuli/facterdb.git` .
3. Try to start the VM by `cd facterdb/facts && vagrant up --provision` then get the following messages. Please find the full log file attached.

```
    debian-10-x86_64: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.                                                                                      
    debian-10-x86_64:                                                                                                                                                         
    debian-10-x86_64: current directory:                                                                                                                                      
    debian-10-x86_64: /home/vagrant/vendor/bundler/ruby/2.7.0/gems/ffi-1.16.3/ext/ffi_c                                                                                       
    debian-10-x86_64: /opt/puppetlabs/puppet/bin/ruby -I /opt/puppetlabs/puppet/lib/ruby/2.7.0 -r                                                                             
    debian-10-x86_64: ./siteconf20231011-3649-1oes40w.rb extconf.rb                                                                                                           
    debian-10-x86_64: checking for ffi.h... *** extconf.rb failed ***                                                                                                         
    debian-10-x86_64: Could not create Makefile due to some reason, probably lack of necessary                                                                                
    debian-10-x86_64: libraries and/or headers.  Check the mkmf.log file for more details.  You may                                                                           
    debian-10-x86_64: need configuration options.                                                     
...
```

[vagrantlog.txt](https://github.com/voxpupuli/facterdb/files/12867327/vagrantlog.txt)
